### ISSUE TITLE
aura: Prelude.head: empty list

### ISSUE THREAD

**Issue by sirus20x6** [aurapm/aura#151]
It's back?

```
sudo aura -Akua
[sudo] password for root: 
aura >>= Fetching package information...
aura >>= Comparing package versions...                                                                                                                                             
aura >>= AUR Packages to upgrade:                                                                                                                                                  
exfat : 1.2.4-4 => 1.2.4-5
kdeconnect-git : 71f9f9d-1 => 103.71f9f9d-1
linux-ck : 3.10.7-2 => 3.10.10-1
nvidia-ck : 325.15-3 => 325.15-5
```

....
yada yada yada
....

```
aura >>= `linux-ck` PKGBUILD is up to date.
aura >>= `nvidia-ck` PKGBUILD changes:
--- a/nvidia-ck/PKGBUILD
+++ b/nvidia-ck/PKGBUILD
@@ -5,7 +5,7 @@
 pkgname=nvidia-ck
 pkgver=325.15
 _extramodules=extramodules-3.10-ck
-pkgrel=3
+pkgrel=5
 _pkgdesc="NVIDIA drivers for linux-ck."
 pkgdesc="$_pkgdesc"
 arch=('i686' 'x86_64')

aura >>= Determining dependencies...
aura: Prelude.head: empty list
```

**Comment by beatgammit** [comment]
It's been a while, so I just wanted to chime in that I've had problems with this recently. For me, it's one of:

- arm-linux-gnueabihf-binutils
- arm-linux-gnueabihf-gcc-stage2
- arm-linux-gnueabihf-glibc

I can narrow that down a bit if you like, but each of these takes a while to compile so it would be better to use a different package instead (though, I suppose you don't need to wait for it to compile).

**Comment by flounders** [comment]
I'm running into the same issue now too. It seems to be arm-linux-gnueabihf-glibc that's causing the problem for me.

**Comment by beatgammit** [comment]
If I ignore `arm-linux-gnueabihf-glibc`, then it works fine. So confirmed, that is one package that has the issue consistently.

**Comment by damienflament** [comment]
I have the same issue when upgrading `visual-studio-code` AUR package.

Pacman v5.0.2
libalpm v10.0.2
Aura version 1.4.0 (built from source using Stack)

**Comment by damienflament** [comment]
The `visual-studio-code` package has been deleted and replaced by `visual-studio-code-bin`.

But Aura still find the PKGBUILD and fail with a `Prelude.head: empty list` error.

**Comment by fosskers** [comment]
This will be fixed soon.

**Comment by 0rvar** [comment]
I am having the same issue with arm-linux-gnueabihf-glibc

**Comment by fosskers** [comment]
Aura doesn't have any `head` calls anymore, so this should be fixed.

**Comment by mateusfccp** [comment]
I still have this problem with aura 1.4.0.

**Comment by fosskers** [comment]
Aura 2.0 will be released very soon, @mateusfccp .

**Comment by Lythenas** [comment]
It's been over a year. I'm still having this problem (on v1.4.0). Was there already a 2.0 release? If so, it's not in the github releases or on the AUR.
